### ISSUE TITLE
[MARKET] Add TKMK market

### ISSUE THREAD

**Issue by Tokamakonsolana** [step-finance/serum-markets#19]
**Token information**

- Token Symbol: TKMK
- Token Mint: TKMKgSh3aADsmjr4yFWG52tkCQvmDxsQC1he1aBsi65
- Serum V3 USDC Market: GcuEE7dHtufcnivcKmXaFZm7HUy9cVrrKupu2LN8GbtK

**Comment by aaronovz1** [comment]
Please fix syntax error in PR :+1:

**Comment by aaronovz1** [comment]
Merged
